name: BACKEND WIKUKARNO CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # Step 1: Setup and Test Laravel Application
  wikukarnocom:
    runs-on: ubuntu-latest

    steps:
      # Step 1.1: Setup PHP Environment
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, tokenizer, fileinfo

      # Step 1.2: Checkout the Repository
      - uses: actions/checkout@v3

      # Step 1.3: Setup Environment File
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Step 1.4: Install Dependencies
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist --optimize-autoloader

      # Step 1.5: Generate Application Key
      - name: Generate Application Key
        run: php artisan key:generate

      # Step 1.6: Run Tests (Optional)
      # Uncomment if you have tests setup
      # - name: Run Tests
      #   run: php artisan test

  # Step 2: Deploy to VPS
  deploy:
    needs: wikukarnocom
    runs-on: ubuntu-latest

    steps:
      # Step 2.1: Checkout the Repository (required for SSH deployment)
      - uses: actions/checkout@v3

      # Step 2.2: Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/api.wikukarno.com
            sudo chown -R www-data:www-data /var/www/api.wikukarno.com
            cd /var/www/api.wikukarno.com
            sudo git pull origin master
            sudo composer install --no-ansi --no-interaction --prefer-dist --optimize-autoloader
            sudo php artisan migrate --force
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan storage:link